import { db } from "@my-app/db";
import { ytTranscript, ytVideo } from "@my-app/db/schema/youtube";
import { downloadAudio } from "@my-app/youtube/download-audio";
import type { ProxyEnv } from "@my-app/youtube/page";
import { getSubtitles, parseTimedSegments } from "@my-app/youtube/subtitles";
import { and, eq } from "drizzle-orm";
import {
	type QueueProducer,
	type R2WritableBucketLike,
	type YtIngestQueueMessage,
	ytQueueKinds,
} from "../../contracts/youtube-queue";

export interface YtIngestDependencies {
	proxyEnv?: ProxyEnv;
	ytNlpQueue?: QueueProducer;
	ytTranscribeQueue?: QueueProducer;
	ytTranscriptsBucket?: R2WritableBucketLike;
}

export interface ProcessYtIngestMessageOptions {
	dependencies: YtIngestDependencies;
	message: YtIngestQueueMessage;
}

const ingestViaCaptions = async (
	transcriptId: string,
	videoId: string,
	organizationId: string,
	youtubeVideoId: string,
	dependencies: YtIngestDependencies
) => {
	const t0 = performance.now();
	console.log(
		`[yt-ingest] Captions path: fetching subtitles for ${youtubeVideoId}`
	);

	const tSubs0 = performance.now();
	const subs = await getSubtitles(
		{
			youtubeVideoId,
			languages: ["en"],
			autoGenerated: true,
			fallbackToAny: true,
		},
		dependencies.proxyEnv
	);
	console.log(
		`[yt-ingest] getSubtitles returned ${subs.length} result(s) for ${youtubeVideoId} in ${Math.round(performance.now() - tSubs0)}ms: ` +
			`${subs.map((s) => `${s.language}/${s.source}(${s.rawData.length}b)`).join(", ") || "none"}`
	);
	const best = subs[0];
	if (!best) {
		await db
			.update(ytVideo)
			.set({ captionsAvailable: false, autoCaptionsAvailable: false })
			.where(eq(ytVideo.id, videoId));
		throw new Error(`No captions available for video ${youtubeVideoId}`);
	}

	const captionsAvailable = subs.some((s) => s.source === "youtube_captions");
	const autoCaptionsAvailable = subs.some((s) => s.source === "auto_generated");

	const tParse0 = performance.now();
	const timedSegments = parseTimedSegments(best.rawData);
	console.log(
		`[yt-ingest] parseTimedSegments: ${timedSegments.length} segments in ${Math.round(performance.now() - tParse0)}ms`
	);

	const tDb0 = performance.now();
	await db.insert(ytTranscript).values({
		id: transcriptId,
		videoId,
		organizationId,
		source: "youtube_captions",
		language: best.language,
		fullText: best.fullText,
		timedSegments: timedSegments.length > 0 ? timedSegments : null,
		segmentCount: timedSegments.length || null,
		durationSeconds:
			timedSegments.length > 0
				? Math.ceil(timedSegments.at(-1)?.end ?? 0)
				: null,
	});

	await db
		.update(ytVideo)
		.set({
			status: "ingested",
			ingestedAt: new Date(),
			captionsAvailable,
			autoCaptionsAvailable,
		})
		.where(eq(ytVideo.id, videoId));
	console.log(
		`[yt-ingest] DB writes (transcript insert + video update) in ${Math.round(performance.now() - tDb0)}ms`
	);

	const dispatchMessage = { transcriptId, videoId, organizationId };

	// Pipeline: ingest → NLP → vectorize → cluster (sequential)
	if (dependencies.ytNlpQueue) {
		const tQueue0 = performance.now();
		await dependencies.ytNlpQueue.send(
			{ kind: ytQueueKinds.nlp, ...dispatchMessage },
			{ contentType: "json" }
		);
		console.log(
			`[yt-ingest] NLP queue send in ${Math.round(performance.now() - tQueue0)}ms`
		);
	}

	console.log(
		`[yt-ingest] ingestViaCaptions total: ${Math.round(performance.now() - t0)}ms for ${youtubeVideoId}`
	);
};

const ingestViaAsr = async (
	transcriptId: string,
	videoId: string,
	organizationId: string,
	youtubeVideoId: string,
	dependencies: YtIngestDependencies
) => {
	const t0 = performance.now();
	console.log(`[yt-ingest] ASR path: downloading audio for ${youtubeVideoId}`);

	const tAudio0 = performance.now();
	const audio = await downloadAudio(
		{ youtubeVideoId, format: "m4a" },
		dependencies.proxyEnv
	);
	console.log(
		`[yt-ingest] downloadAudio: ${audio.data.byteLength}b ${audio.contentType} in ${Math.round(performance.now() - tAudio0)}ms`
	);
	const audioR2Key = `audio/${organizationId}/${videoId}.${audio.extension}`;
	const audioContentType = audio.contentType;

	if (dependencies.ytTranscriptsBucket) {
		const tR20 = performance.now();
		await dependencies.ytTranscriptsBucket.put(audioR2Key, audio.data);
		console.log(
			`[yt-ingest] R2 upload (${audio.data.byteLength}b) in ${Math.round(performance.now() - tR20)}ms`
		);
	}

	const tDb0 = performance.now();
	await db.insert(ytTranscript).values({
		id: transcriptId,
		videoId,
		organizationId,
		source: "whisper_asr",
		language: "en",
		fullText: "",
	});

	await db
		.update(ytVideo)
		.set({ status: "ingested", ingestedAt: new Date(), audioR2Key })
		.where(eq(ytVideo.id, videoId));
	console.log(
		`[yt-ingest] DB writes (transcript insert + video update) in ${Math.round(performance.now() - tDb0)}ms`
	);

	if (dependencies.ytTranscribeQueue) {
		const tQueue0 = performance.now();
		await dependencies.ytTranscribeQueue.send(
			{
				kind: ytQueueKinds.transcribe,
				transcriptId,
				videoId,
				organizationId,
				audioR2Key,
				contentType: audioContentType,
			},
			{ contentType: "json" }
		);
		console.log(
			`[yt-ingest] Transcribe queue send in ${Math.round(performance.now() - tQueue0)}ms`
		);
	}

	console.log(
		`[yt-ingest] ingestViaAsr total: ${Math.round(performance.now() - t0)}ms for ${youtubeVideoId}`
	);
};

export const processYtIngestMessage = async ({
	message,
	dependencies,
}: ProcessYtIngestMessageOptions): Promise<void> => {
	const { videoId, organizationId, youtubeVideoId, forceAsr, enableAsr } =
		message;
	const tTotal0 = performance.now();

	try {
		const tStatus0 = performance.now();
		await db
			.update(ytVideo)
			.set({ status: "ingesting" })
			.where(
				and(eq(ytVideo.id, videoId), eq(ytVideo.organizationId, organizationId))
			);
		console.log(
			`[yt-ingest] Status → ingesting in ${Math.round(performance.now() - tStatus0)}ms`
		);

		console.log(
			`[yt-ingest] Processing video ${youtubeVideoId} (id: ${videoId}, forceAsr: ${forceAsr}, enableAsr: ${enableAsr})`
		);

		const transcriptId = crypto.randomUUID();

		if (forceAsr) {
			await ingestViaAsr(
				transcriptId,
				videoId,
				organizationId,
				youtubeVideoId,
				dependencies
			);
		} else {
			try {
				await ingestViaCaptions(
					transcriptId,
					videoId,
					organizationId,
					youtubeVideoId,
					dependencies
				);
			} catch (captionError) {
				const isNoCaptions =
					captionError instanceof Error &&
					captionError.message.startsWith("No captions available");
				if (!isNoCaptions) {
					throw captionError;
				}

				if (!enableAsr) {
					console.log(
						`[yt-ingest] No captions for ${youtubeVideoId} and ASR is disabled for this feed — skipping (captionsAvailable=false written)`
					);
					// Gracefully reset to approved so the video isn't marked failed.
					// captionsAvailable / autoCaptionsAvailable were already written by
					// ingestViaCaptions before it threw, so the UI will show "no captions".
					await db
						.update(ytVideo)
						.set({ status: "approved" })
						.where(eq(ytVideo.id, videoId));
					return; // ACK the queue message — nothing to retry
				}

				console.log(
					`[yt-ingest] No captions for ${youtubeVideoId}, falling back to ASR`
				);
				await ingestViaAsr(
					transcriptId,
					videoId,
					organizationId,
					youtubeVideoId,
					dependencies
				);
			}
		}

		console.log(
			`[yt-ingest] processYtIngestMessage total: ${Math.round(performance.now() - tTotal0)}ms for ${youtubeVideoId}`
		);
	} catch (error) {
		console.error(
			`[yt-ingest] processYtIngestMessage failed after ${Math.round(performance.now() - tTotal0)}ms for ${youtubeVideoId}:`,
			error
		);
		await db
			.update(ytVideo)
			.set({
				status: "failed",
				failureReason: error instanceof Error ? error.message : "Unknown error",
				failedStage: "ingest",
			})
			.where(eq(ytVideo.id, videoId));

		throw error;
	}
};
