import { db } from "@my-app/db";
import { ytTranscript, ytVideo } from "@my-app/db/schema/youtube";
import { downloadAudio } from "@my-app/youtube/download-audio";
import { getSubtitles, parseTimedSegments } from "@my-app/youtube/subtitles";
import { and, eq } from "drizzle-orm";
import {
	type QueueProducer,
	type R2WritableBucketLike,
	type YtIngestQueueMessage,
	ytQueueKinds,
} from "../../contracts/youtube-queue";

export interface YtIngestDependencies {
	ytNlpQueue?: QueueProducer;
	ytTranscribeQueue?: QueueProducer;
	ytTranscriptsBucket?: R2WritableBucketLike;
}

export interface ProcessYtIngestMessageOptions {
	dependencies: YtIngestDependencies;
	message: YtIngestQueueMessage;
}

const ingestViaCaptions = async (
	transcriptId: string,
	videoId: string,
	organizationId: string,
	youtubeVideoId: string,
	dependencies: YtIngestDependencies
) => {
	console.log(
		`[yt-ingest] Captions path: fetching subtitles for ${youtubeVideoId}`
	);

	const subs = await getSubtitles({
		youtubeVideoId,
		languages: ["en"],
		autoGenerated: true,
	});
	console.log(
		`[yt-ingest] getSubtitles returned ${subs.length} result(s) for ${youtubeVideoId}: ` +
			`${subs.map((s) => `${s.language}/${s.source}(${s.rawData.length}b)`).join(", ") || "none"}`
	);
	const best = subs[0];
	if (!best) {
		throw new Error(`No captions available for video ${youtubeVideoId}`);
	}

	const timedSegments = parseTimedSegments(best.rawData);

	await db.insert(ytTranscript).values({
		id: transcriptId,
		videoId,
		organizationId,
		source: "youtube_captions",
		language: best.language,
		fullText: best.fullText,
		timedSegments: timedSegments.length > 0 ? timedSegments : null,
		segmentCount: timedSegments.length || null,
		durationSeconds:
			timedSegments.length > 0
				? Math.ceil(timedSegments.at(-1)?.end ?? 0)
				: null,
	});

	await db
		.update(ytVideo)
		.set({ status: "ingested", ingestedAt: new Date() })
		.where(eq(ytVideo.id, videoId));

	const dispatchMessage = { transcriptId, videoId, organizationId };

	// Pipeline: ingest → NLP → vectorize → cluster (sequential)
	if (dependencies.ytNlpQueue) {
		await dependencies.ytNlpQueue.send(
			{ kind: ytQueueKinds.nlp, ...dispatchMessage },
			{ contentType: "json" }
		);
	}
};

const ingestViaAsr = async (
	transcriptId: string,
	videoId: string,
	organizationId: string,
	youtubeVideoId: string,
	dependencies: YtIngestDependencies
) => {
	console.log(`[yt-ingest] ASR path: downloading audio for ${youtubeVideoId}`);

	const audio = await downloadAudio({ youtubeVideoId, format: "m4a" });
	const audioR2Key = `audio/${organizationId}/${videoId}.${audio.extension}`;
	const audioContentType = audio.contentType;

	if (dependencies.ytTranscriptsBucket) {
		await dependencies.ytTranscriptsBucket.put(audioR2Key, audio.data);
	}

	await db.insert(ytTranscript).values({
		id: transcriptId,
		videoId,
		organizationId,
		source: "whisper_asr",
		language: "en",
		fullText: "",
	});

	await db
		.update(ytVideo)
		.set({ status: "ingested", ingestedAt: new Date() })
		.where(eq(ytVideo.id, videoId));

	if (dependencies.ytTranscribeQueue) {
		await dependencies.ytTranscribeQueue.send(
			{
				kind: ytQueueKinds.transcribe,
				transcriptId,
				videoId,
				organizationId,
				audioR2Key,
				contentType: audioContentType,
			},
			{ contentType: "json" }
		);
	}
};

export const processYtIngestMessage = async ({
	message,
	dependencies,
}: ProcessYtIngestMessageOptions): Promise<void> => {
	const { videoId, organizationId, youtubeVideoId, forceAsr } = message;

	try {
		await db
			.update(ytVideo)
			.set({ status: "ingesting" })
			.where(
				and(eq(ytVideo.id, videoId), eq(ytVideo.organizationId, organizationId))
			);

		console.log(
			`[yt-ingest] Processing video ${youtubeVideoId} (id: ${videoId}, forceAsr: ${forceAsr})`
		);

		const transcriptId = crypto.randomUUID();

		if (forceAsr) {
			await ingestViaAsr(
				transcriptId,
				videoId,
				organizationId,
				youtubeVideoId,
				dependencies
			);
		} else {
			try {
				await ingestViaCaptions(
					transcriptId,
					videoId,
					organizationId,
					youtubeVideoId,
					dependencies
				);
			} catch (captionError) {
				const isNoCaptions =
					captionError instanceof Error &&
					captionError.message.startsWith("No captions available");
				if (!isNoCaptions) {
					throw captionError;
				}

				console.log(
					`[yt-ingest] No captions for ${youtubeVideoId}, falling back to ASR`
				);
				await ingestViaAsr(
					transcriptId,
					videoId,
					organizationId,
					youtubeVideoId,
					dependencies
				);
			}
		}
	} catch (error) {
		await db
			.update(ytVideo)
			.set({
				status: "failed",
				failureReason: error instanceof Error ? error.message : "Unknown error",
				failedStage: "ingest",
			})
			.where(eq(ytVideo.id, videoId));

		throw error;
	}
};
