/**
 * E2E test: YouTube Intelligence Pipeline
 *
 * Tests the full subtitle → NLP → vectorize → cluster pipeline using
 * a real YouTube video (vYNPV6F4BqU) with timed subtitle segments.
 *
 * Runs against an in-memory SQLite DB — no network calls except subtitle fetch.
 */

import { organization, user } from "@my-app/db/schema/auth";
import {
	ytCluster,
	ytFeed,
	ytSignal,
	ytTranscript,
	ytVideo,
} from "@my-app/db/schema/youtube";
import { bootstrapTestDatabase, type TestDatabase } from "@my-app/db/test";
import {
	getSubtitles,
	parseTimedSegments,
	type TimedSegment,
} from "@my-app/youtube/subtitles";
import { eq } from "drizzle-orm";
import { describe, expect, it, vi } from "vitest";

// ─── Test DB Setup ───────────────────────────────────────────────────────────

const VIDEO_ID = "vYNPV6F4BqU";
const ORG_ID = "org-test-intel";
const FEED_ID = "feed-test-intel";
const DB_VIDEO_ID = "vid-test-intel";
const USER_ID = "user-test-intel";

const testDbState = bootstrapTestDatabase({
	seed: async (db: TestDatabase) => {
		await db.insert(user).values({
			id: USER_ID,
			name: "Test User",
			email: "test-intel@example.com",
			emailVerified: true,
		});
		await db.insert(organization).values({
			id: ORG_ID,
			name: "Test Org",
			slug: "test-intel-org",
		});
		await db.insert(ytFeed).values({
			id: FEED_ID,
			organizationId: ORG_ID,
			name: "Test Feed",
			gameTitle: "Test Game",
			searchQuery: "test",
		});
		await db.insert(ytVideo).values({
			id: DB_VIDEO_ID,
			feedId: FEED_ID,
			organizationId: ORG_ID,
			youtubeVideoId: VIDEO_ID,
			title: "Test Video",
			status: "ingested",
		});
	},
	seedStrategy: "beforeAll",
});

// Replace db module so services use our test DB
vi.doMock("@my-app/db", () => ({
	db: testDbState.db,
}));

// Dynamic imports after mock
const { processYtNlpMessage, resolveTimestampFromSegments } = await import(
	"../services/youtube/nlp"
);
const { processYtVectorizeMessage } = await import(
	"../services/youtube/vectorize"
);
const { processYtClusterMessage } = await import("../services/youtube/cluster");

const db = testDbState.db;

// ─── Tests ───────────────────────────────────────────────────────────────────

describe("YouTube Intelligence Pipeline E2E", () => {
	let fullText: string;
	let rawData: string;
	let timedSegments: TimedSegment[];

	describe("1. Subtitle fetching with timed segments", () => {
		it("should fetch subtitles and parse timed segments", async () => {
			const results = await getSubtitles({
				youtubeVideoId: VIDEO_ID,
				languages: ["en"],
				autoGenerated: true,
			});

			expect(results.length).toBeGreaterThan(0);
			const sub = results[0];
			if (!sub) {
				throw new Error("No subtitle result");
			}
			expect(sub.fullText.length).toBeGreaterThan(100);
			expect(sub.rawData.length).toBeGreaterThan(0);

			fullText = sub.fullText;
			rawData = sub.rawData;

			// Parse timed segments
			timedSegments = parseTimedSegments(rawData);
			expect(timedSegments.length).toBeGreaterThan(0);

			// Verify segments have proper timestamps
			for (const seg of timedSegments) {
				expect(seg.start).toBeGreaterThanOrEqual(0);
				expect(seg.end).toBeGreaterThanOrEqual(seg.start);
				expect(seg.text.length).toBeGreaterThan(0);
			}

			// Segments should be roughly in order
			for (let i = 1; i < timedSegments.length; i++) {
				const curr = timedSegments[i];
				const prev = timedSegments[i - 1];
				if (!curr) {
					continue;
				}
				if (!prev) {
					continue;
				}
				expect(curr.start).toBeGreaterThanOrEqual(prev.start);
			}

			console.log(
				`Fetched ${timedSegments.length} timed segments, ` +
					`duration: ${Math.ceil(timedSegments.at(-1)?.end ?? 0)}s, ` +
					`text: ${fullText.length} chars`
			);
		}, 30_000);
	});

	describe("2. resolveTimestampFromSegments", () => {
		it("should map character offsets to video timestamps", () => {
			const segText = timedSegments.map((s) => s.text).join(" ");

			// Offset 0 should map to start of first segment
			const ts0 = resolveTimestampFromSegments(0, segText, timedSegments);
			expect(ts0).toBeDefined();
			expect(ts0).toBeGreaterThanOrEqual(0);

			// A mid-transcript offset should map to a mid-video timestamp
			const midOffset = Math.floor(segText.length / 2);
			const tsMid = resolveTimestampFromSegments(
				midOffset,
				segText,
				timedSegments
			);
			expect(tsMid).toBeDefined();
			if (ts0 != null && tsMid != null) {
				expect(tsMid).toBeGreaterThan(ts0);
			}
		});
	});

	describe("3. Full pipeline: NLP → Vectorize → Cluster", () => {
		it("should extract signals, vectorize, cluster, and produce frontend-ready output", async () => {
			const transcriptId = crypto.randomUUID();

			// ── NLP: Insert transcript and extract signals ──
			await db.insert(ytTranscript).values({
				id: transcriptId,
				videoId: DB_VIDEO_ID,
				organizationId: ORG_ID,
				source: "youtube_captions",
				language: "en",
				fullText,
				timedSegments,
				segmentCount: timedSegments.length,
				durationSeconds: Math.ceil(timedSegments.at(-1)?.end ?? 0),
			});

			const nlpResult = await processYtNlpMessage({
				message: {
					kind: "yt.nlp.v1" as const,
					transcriptId,
					videoId: DB_VIDEO_ID,
					organizationId: ORG_ID,
				},
				dependencies: {},
			});
			expect(nlpResult).toBe("processed");

			const signals = await db
				.select()
				.from(ytSignal)
				.where(eq(ytSignal.transcriptId, transcriptId));
			expect(signals.length).toBeGreaterThan(0);
			console.log(`Extracted ${signals.length} signals`);

			for (const signal of signals) {
				expect(signal.type).toBeTruthy();
				expect(signal.severity).toBeTruthy();
				expect(signal.text.length).toBeGreaterThan(0);
				expect(signal.confidence).toBeGreaterThanOrEqual(0);
				expect(signal.confidence).toBeLessThanOrEqual(100);

				if (signal.timestampStart != null) {
					console.log(
						`  Signal [${signal.type}/${signal.severity}] ` +
							`${formatTime(signal.timestampStart)}-${formatTime(signal.timestampEnd ?? 0)}: ` +
							`"${signal.text.slice(0, 80)}..." ` +
							`tags: ${signal.tags ? JSON.stringify(signal.tags) : "none"}`
					);
				}
			}

			const [transcript] = await db
				.select()
				.from(ytTranscript)
				.where(eq(ytTranscript.id, transcriptId));
			if (!transcript) {
				throw new Error("Transcript not found");
			}
			expect(transcript.nlpStatus).toBe("processed");

			// ── Vectorize: embed all signals ──
			const upsertedVectors: Array<{
				id: string;
				values: number[];
				metadata?: Record<string, string | number | boolean>;
			}> = [];

			const mockVectorizeIndex = {
				upsert: (
					vectors: Array<{
						id: string;
						values: number[];
						metadata?: Record<string, string | number | boolean>;
					}>
				): Promise<unknown> => {
					upsertedVectors.push(...vectors);
					return Promise.resolve();
				},
			};

			const vectorizeResult = await processYtVectorizeMessage({
				message: {
					kind: "yt.vectorize.v1" as const,
					transcriptId,
					videoId: DB_VIDEO_ID,
					organizationId: ORG_ID,
				},
				vectorizeIndex: mockVectorizeIndex,
			});
			expect(vectorizeResult).toBe("processed");
			expect(upsertedVectors.length).toBeGreaterThan(0);

			for (const vec of upsertedVectors) {
				expect(vec.values.length).toBe(1536);
				const magnitude = Math.sqrt(
					vec.values.reduce((sum, v) => sum + v * v, 0)
				);
				expect(magnitude).toBeCloseTo(1, 1);
			}

			const vectorizedSignals = await db
				.select()
				.from(ytSignal)
				.where(eq(ytSignal.transcriptId, transcriptId));
			for (const s of vectorizedSignals) {
				expect(s.vectorized).toBe(true);
				expect(s.embeddingModel).toBe("hash-256");
			}
			console.log(
				`Vectorized ${upsertedVectors.length} signals (1536-dim hash embeddings)`
			);

			// ── Cluster: group signals ──
			for (const signal of vectorizedSignals) {
				const clusterResult = await processYtClusterMessage({
					message: {
						kind: "yt.cluster.v1" as const,
						signalId: signal.id,
						organizationId: ORG_ID,
					},
				});
				expect(["clustered", "already_clustered"]).toContain(clusterResult);
			}

			const clusters = await db
				.select()
				.from(ytCluster)
				.where(eq(ytCluster.organizationId, ORG_ID));
			expect(clusters.length).toBeGreaterThan(0);

			for (const cluster of clusters) {
				expect(cluster.title.length).toBeGreaterThan(0);
				expect(cluster.signalCount).toBeGreaterThanOrEqual(1);
				expect(cluster.state).toBe("open");
			}

			console.log(
				`Created ${clusters.length} clusters from ${vectorizedSignals.length} signals`
			);
			for (const c of clusters) {
				console.log(
					`  Cluster [${c.type}/${c.severity}]: "${c.title.slice(0, 60)}..." ` +
						`(${c.signalCount} signals)`
				);
			}

			// ── Final output: frontend-ready format ──
			const finalSignals = await db
				.select()
				.from(ytSignal)
				.where(eq(ytSignal.transcriptId, transcriptId));

			const output = finalSignals.map((s) => ({
				id: s.id,
				timeRange:
					s.timestampStart != null
						? `${formatTime(s.timestampStart)} - ${formatTime(s.timestampEnd ?? s.timestampStart + 30)}`
						: null,
				category: s.type,
				severity: s.severity,
				confidence: s.confidence ? s.confidence / 100 : null,
				description: s.text.slice(0, 120),
				tags: s.tags,
				component: s.component,
				clusterId: s.clusterId,
				clusterTitle: clusters.find((c) => c.id === s.clusterId)?.title ?? null,
			}));

			console.log("\n═══ Final Intelligence Output ═══");
			for (const item of output) {
				console.log(
					`  ${item.timeRange ?? "??:??-??:??"} | ` +
						`category:${item.category}, score:${item.confidence} | ` +
						`"${item.description}" | ` +
						`tags: ${item.tags?.join(", ") ?? "none"} | ` +
						`cluster: "${item.clusterTitle?.slice(0, 40)}..."`
				);
			}
			console.log("═════════════════════════════════");

			const withTimestamps = output.filter((o) => o.timeRange != null);
			console.log(
				`${withTimestamps.length}/${output.length} signals have video timestamps`
			);

			// All signals should be clustered
			expect(finalSignals.every((s) => s.clusterId)).toBe(true);
		}, 30_000);
	});
});

function formatTime(seconds: number): string {
	const m = Math.floor(seconds / 60)
		.toString()
		.padStart(2, "0");
	const s = Math.floor(seconds % 60)
		.toString()
		.padStart(2, "0");
	return `${m}:${s}`;
}
