#!/usr/bin/env bash
# gen-act-secrets.sh — Populate .act-secrets from Pulumi stack outputs.
#
# Run from the repo root:
#   bash infra/scripts/gen-act-secrets.sh [stack]
#
# Prerequisites: pulumi CLI logged in, PULUMI_CONFIG_PASSPHRASE set (or empty).

set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

STACK="${1:-staging}"
PULUMI_DIR="infra/pulumi"
OUT=".act-secrets"
OUT_PATH="$(pwd)/${OUT}"

echo "→ Reading stack '${STACK}' outputs from ${PULUMI_DIR}..."

if ! command -v pulumi >/dev/null 2>&1; then
  echo "✗ pulumi CLI not found in PATH"
  exit 1
fi

if ! command -v python3 >/dev/null 2>&1; then
  echo "✗ python3 not found in PATH"
  exit 1
fi

(
  cd "${PULUMI_DIR}"
  export PULUMI_CONFIG_PASSPHRASE="${PULUMI_CONFIG_PASSPHRASE:-}"

  SSH_JSON=$(pulumi stack output ssh --json --stack "${STACK}")
  SSH_PRIVATE_KEY_B64=$(pulumi stack output deployPrivateKeyB64 --show-secrets --stack "${STACK}" 2>/dev/null || true)

  if [[ -z "${SSH_PRIVATE_KEY_B64}" || "${SSH_PRIVATE_KEY_B64}" == "null" ]]; then
    echo "✗ Missing stack output 'deployPrivateKeyB64' for stack '${STACK}'."
    echo "  Run: cd ${PULUMI_DIR} && pulumi up --stack ${STACK}"
    exit 1
  fi

  SSH_HOST=$(python3 -c "import json,sys; print(json.load(sys.stdin)['host'])" <<<"${SSH_JSON}")
  SSH_USER=$(python3 -c "import json,sys; print(json.load(sys.stdin)['user'])" <<<"${SSH_JSON}")
  SSH_PORT=$(python3 -c "import json,sys; print(json.load(sys.stdin)['port'])" <<<"${SSH_JSON}")

  if command -v gh >/dev/null 2>&1; then
    GITHUB_TOKEN=$(gh auth token 2>/dev/null || echo "FILL_IN_GITHUB_TOKEN")
  else
    GITHUB_TOKEN="FILL_IN_GITHUB_TOKEN"
  fi

  cat > "${OUT_PATH}" << EOF
# .act-secrets — generated by infra/scripts/gen-act-secrets.sh
# DO NOT COMMIT — this file is gitignored.
SSH_HOST=${SSH_HOST}
SSH_USER=${SSH_USER}
SSH_PORT=${SSH_PORT}
SSH_PRIVATE_KEY_B64=${SSH_PRIVATE_KEY_B64}
GITHUB_TOKEN=${GITHUB_TOKEN}
GITLEAKS_LICENSE=
EOF
  chmod 600 "${OUT_PATH}"
  echo "✓ Written to ${OUT}"
)
