#!/usr/bin/env bash
# gen-act-secrets.sh — Populate .act-secrets from Pulumi stack outputs.
#
# Run from the repo root:
#   bash infra/scripts/gen-act-secrets.sh [stack]
#
# Prerequisites: pulumi CLI logged in, PULUMI_CONFIG_PASSPHRASE set (or empty).

set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

STACK="${1:-staging}"
PULUMI_DIR="infra/pulumi"
OUT=".act-secrets"

echo "→ Reading stack '${STACK}' outputs from ${PULUMI_DIR}..."

# Temporarily export the private key as a stack output so we can read it.
# We patch index.ts, run pulumi up (no-op), read the output, then restore.
INDEX="${PULUMI_DIR}/src/index.ts"
PATCH='export const _actKey = deployKey.privateKeyOpenssh.apply((k: string) => Buffer.from(k).toString("base64"));'

# Add temp export if not already there
if ! grep -q "_actKey" "${INDEX}"; then
  echo "${PATCH}" >> "${INDEX}"
  ADDED=1
fi

(
  cd "${PULUMI_DIR}"
  export PULUMI_CONFIG_PASSPHRASE="${PULUMI_CONFIG_PASSPHRASE:-}"
  pulumi up --yes --stack "${STACK}" 2>/dev/null || true

  SSH_PRIVATE_KEY_B64=$(pulumi stack output _actKey --show-secrets --stack "${STACK}" 2>/dev/null)
  SSH_HOST=$(pulumi stack output ssh --json --stack "${STACK}" 2>/dev/null | python3 -c "import json,sys; print(json.load(sys.stdin)['host'])")
  SSH_USER=$(pulumi stack output ssh --json --stack "${STACK}" 2>/dev/null | python3 -c "import json,sys; print(json.load(sys.stdin)['user'])")
  SSH_PORT=$(pulumi stack output ssh --json --stack "${STACK}" 2>/dev/null | python3 -c "import json,sys; print(json.load(sys.stdin)['port'])")

  cd - > /dev/null
  cat > "${OUT}" << EOF
# .act-secrets — generated by infra/scripts/gen-act-secrets.sh
# DO NOT COMMIT — this file is gitignored.
SSH_HOST=${SSH_HOST}
SSH_USER=${SSH_USER}
SSH_PORT=${SSH_PORT}
SSH_PRIVATE_KEY_B64=${SSH_PRIVATE_KEY_B64}
GITHUB_TOKEN=$(gh auth token 2>/dev/null || echo "FILL_IN_GITHUB_TOKEN")
GITLEAKS_LICENSE=
EOF
  echo "✓ Written to ${OUT}"
)

# Remove the temp export
if [[ "${ADDED:-0}" == "1" ]]; then
  # Remove the last line we added
  sed -i '' '/^export const _actKey/d' "${INDEX}"
  (
    cd "${PULUMI_DIR}"
    export PULUMI_CONFIG_PASSPHRASE="${PULUMI_CONFIG_PASSPHRASE:-}"
    pulumi up --yes --stack "${STACK}" 2>/dev/null || true
  )
fi
