#!/usr/bin/env bash
# write-vps-env.sh — Generate runtime .env and upload it to VPS atomically.
#
# Usage:
#   IMAGE_PREFIX=ghcr.io/org/repo GIT_SHA=abc123 \
#   DOMAIN=example.com ACME_EMAIL=ops@example.com \
#   ... \
#   bash infra/scripts/write-vps-env.sh --env staging --deploy-path /srv/app

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=infra/scripts/lib/vps-common.sh
source "${SCRIPT_DIR}/lib/vps-common.sh"
ROOT_DIR="$(vps_repo_root_from_script_dir "${SCRIPT_DIR}")"

usage() {
  cat <<'USAGE'
Usage: bash infra/scripts/write-vps-env.sh [options]

Options:
  --env <staging|production|name>   Environment name (default: staging)
  --host <ip-or-hostname>           VPS SSH host (default: from .vps/<env>.ip)
  --user <ssh-user>                 SSH user (default: deploy)
  --port <ssh-port>                 SSH port (default: 22)
  --key <path>                      SSH private key path (default: auto-detect, else SSH agent)
  --deploy-path <path>              Remote deploy path (default: /srv/app)
  -h, --help                        Show help

Required environment variables:
  BETTER_AUTH_SECRET, POSTGRES_PASSWORD, GRAFANA_PASSWORD,
  OPEN_ROUTER_API_KEY, DOMAIN, ACME_EMAIL, POSTGRES_USER, POSTGRES_DB,
  SMTP_HOST, SMTP_PORT, SMTP_FROM, AI_MODEL, LOKI_URL, GRAFANA_PORT,
  GRAFANA_ALERT_EMAIL, NODE_ENV, IMAGE_PREFIX, GIT_SHA

Optional environment variables:
  OPENAI_API_KEY, TELEGRAM_BOT_TOKEN, TELEGRAM_CHAT_ID,
  SMTP_USER, SMTP_PASS, TELEGRAM_BOT_USERNAME
USAGE
}

ENV_NAME="staging"
HOST="${SSH_HOST:-}"
SSH_USER_NAME="${SSH_USER:-deploy}"
SSH_PORT_VALUE="${SSH_PORT:-22}"
KEY_PATH="${SSH_KEY_PATH:-}"
DEPLOY_PATH_VALUE="${DEPLOY_PATH:-/srv/app}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --env)
      ENV_NAME="${2:-}"
      shift 2
      ;;
    --host)
      HOST="${2:-}"
      shift 2
      ;;
    --user)
      SSH_USER_NAME="${2:-}"
      shift 2
      ;;
    --port)
      SSH_PORT_VALUE="${2:-}"
      shift 2
      ;;
    --key)
      KEY_PATH="${2:-}"
      shift 2
      ;;
    --deploy-path)
      DEPLOY_PATH_VALUE="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Error: unknown option '$1'" >&2
      usage >&2
      exit 1
      ;;
  esac
done

HOST="$(vps_resolve_host "${HOST}" "${ROOT_DIR}" "${ENV_NAME}")"
KEY_PATH="$(vps_resolve_key_path "${KEY_PATH}" "${ENV_NAME}")"
DEPLOY_PATH_VALUE="$(vps_expand_path "${DEPLOY_PATH_VALUE}")"

required_env=(
  BETTER_AUTH_SECRET
  POSTGRES_PASSWORD
  GRAFANA_PASSWORD
  OPEN_ROUTER_API_KEY
  DOMAIN
  ACME_EMAIL
  POSTGRES_USER
  POSTGRES_DB
  SMTP_HOST
  SMTP_PORT
  SMTP_FROM
  AI_MODEL
  LOKI_URL
  GRAFANA_PORT
  GRAFANA_ALERT_EMAIL
  NODE_ENV
  IMAGE_PREFIX
  GIT_SHA
)

missing_env=()
for key in "${required_env[@]}"; do
  if [[ -z "${!key:-}" ]]; then
    missing_env+=("${key}")
  fi
done

if [[ ${#missing_env[@]} -gt 0 ]]; then
  echo "Error: missing required environment variable(s): ${missing_env[*]}" >&2
  exit 1
fi

vps_require_cmd ssh
vps_require_cmd scp
vps_require_cmd mktemp

BETTER_AUTH_URL="https://${DOMAIN}"
SERVER_URL="https://api.${DOMAIN}"
CORS_ORIGIN="https://${DOMAIN}"
PUBLIC_SERVER_URL="https://api.${DOMAIN}"
PUBLIC_ASSISTANT_URL="https://assistant.${DOMAIN}"

tmp_env="$(mktemp)"
cleanup() {
  rm -f "${tmp_env}"
}
trap cleanup EXIT

umask 077
cat > "${tmp_env}" <<EOF
# Auto-generated by infra/scripts/write-vps-env.sh — do not edit manually.

# Registry images
SERVER_IMAGE=${IMAGE_PREFIX}/server:sha-${GIT_SHA}
ASSISTANT_IMAGE=${IMAGE_PREFIX}/assistant:sha-${GIT_SHA}
NOTIFICATIONS_IMAGE=${IMAGE_PREFIX}/notifications:sha-${GIT_SHA}
WEB_IMAGE=${IMAGE_PREFIX}/web:sha-${GIT_SHA}

# App (URLs derived from DOMAIN)
BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
BETTER_AUTH_URL=${BETTER_AUTH_URL}
SERVER_URL=${SERVER_URL}
CORS_ORIGIN=${CORS_ORIGIN}
PUBLIC_SERVER_URL=${PUBLIC_SERVER_URL}
PUBLIC_ASSISTANT_URL=${PUBLIC_ASSISTANT_URL}

# Database
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${POSTGRES_DB}
DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}

# AI
OPEN_ROUTER_API_KEY=${OPEN_ROUTER_API_KEY}
OPENAI_API_KEY=${OPENAI_API_KEY:-}
AI_MODEL=${AI_MODEL}

# Email
SMTP_HOST=${SMTP_HOST}
SMTP_PORT=${SMTP_PORT}
SMTP_FROM=${SMTP_FROM}
SMTP_USER=${SMTP_USER:-}
SMTP_PASS=${SMTP_PASS:-}

# Alerting
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
TELEGRAM_BOT_USERNAME=${TELEGRAM_BOT_USERNAME:-}
TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID:-}
GRAFANA_ALERT_EMAIL=${GRAFANA_ALERT_EMAIL}

# Observability
LOKI_URL=${LOKI_URL}
GRAFANA_PORT=${GRAFANA_PORT}
GRAFANA_PASSWORD=${GRAFANA_PASSWORD}

# Traefik
DOMAIN=${DOMAIN}
ACME_EMAIL=${ACME_EMAIL}

# Runtime
NODE_ENV=${NODE_ENV}
TURBO_TELEMETRY_MESSAGE_DISABLED=true
EOF

SSH_OPTS=(
  -p "${SSH_PORT_VALUE}"
  -o BatchMode=yes
  -o ConnectTimeout=12
  -o StrictHostKeyChecking=accept-new
)

SCP_OPTS=(
  -P "${SSH_PORT_VALUE}"
  -o BatchMode=yes
  -o ConnectTimeout=12
  -o StrictHostKeyChecking=accept-new
)

if [[ -n "${KEY_PATH}" ]]; then
  SSH_OPTS=(-i "${KEY_PATH}" "${SSH_OPTS[@]}")
  SCP_OPTS=(-i "${KEY_PATH}" "${SCP_OPTS[@]}")
fi

echo "== VPS .env Write =="
echo "env=${ENV_NAME} host=${HOST} user=${SSH_USER_NAME} port=${SSH_PORT_VALUE} deploy_path=${DEPLOY_PATH_VALUE}"
echo "images_tag=sha-${GIT_SHA}"
echo

if ! ssh "${SSH_OPTS[@]}" "${SSH_USER_NAME}@${HOST}" "mkdir -p '${DEPLOY_PATH_VALUE}'"; then
  echo "ERROR: failed to prepare deploy path '${DEPLOY_PATH_VALUE}' on ${HOST}." >&2
  exit 1
fi

if ! scp "${SCP_OPTS[@]}" "${tmp_env}" "${SSH_USER_NAME}@${HOST}:${DEPLOY_PATH_VALUE}/.env.tmp"; then
  echo "ERROR: failed to upload .env.tmp to '${DEPLOY_PATH_VALUE}'." >&2
  exit 1
fi

ssh "${SSH_OPTS[@]}" "${SSH_USER_NAME}@${HOST}" \
  "chmod 600 '${DEPLOY_PATH_VALUE}/.env.tmp' && mv '${DEPLOY_PATH_VALUE}/.env.tmp' '${DEPLOY_PATH_VALUE}/.env' && echo '.env written to ${DEPLOY_PATH_VALUE}/.env'"
