export const CLEANUP_TABLES = [
	"booking_cancellation_request",
	"booking",
	"listing_publication",
	"cancellation_policy",
	"listing_pricing_profile",
	"listing",
	"organization_payment_config",
	"organization_settings",
	"payment_provider_config",
	"listing_type_config",
	"assistant_message",
	"assistant_chat",
	"notification_in_app",
	"notification_delivery",
	"notification_intent",
	"notification_event",
	"notification_preference",
	"user_consent",
	"passkey",
	"verification",
	"invitation",
	"member",
	"account",
	"session",
	"organization",
] as const;
