import z from "zod";
import { fetchPlayerResponse } from "./page";

// ─── Schemas ─────────────────────────────────────────────────────────────────

export const subtitleOptionsSchema = z.object({
	youtubeVideoId: z.string().trim().min(1),
	languages: z.array(z.string()).default(["en"]),
	/** If true, try auto-generated captions when manual subs unavailable */
	autoGenerated: z.boolean().default(true),
});

export type SubtitleOptions = z.infer<typeof subtitleOptionsSchema>;

export interface SubtitleResult {
	/** Full text content of the subtitles */
	fullText: string;
	language: string;
	/** Raw subtitle data (JSON3 or VTT) */
	rawData: string;
	source: "youtube_captions" | "auto_generated";
}

// ─── Subtitles Implementation ────────────────────────────────────────────────

interface CaptionTrack {
	baseUrl: string;
	/** Present only on auto-generated tracks */
	kind?: string;
	languageCode: string;
}

/**
 * Download subtitles/captions for a YouTube video.
 *
 * Uses the InnerTube ANDROID client API which returns working caption
 * track URLs without session cookies, compatible with Cloudflare Workers.
 */
export async function getSubtitles(
	options: SubtitleOptions
): Promise<SubtitleResult[]> {
	const playerData = await fetchPlayerResponse(options.youtubeVideoId);

	const captionsRenderer = (
		playerData.captions as Record<string, unknown> | undefined
	)?.playerCaptionsTracklistRenderer as Record<string, unknown> | undefined;

	if (!captionsRenderer) {
		console.warn(
			`[subtitles] No captions renderer in player response for videoId=${options.youtubeVideoId}. ` +
				`Top-level keys: ${Object.keys(playerData).join(", ")}`
		);
		return [];
	}

	const tracks = (captionsRenderer.captionTracks ?? []) as CaptionTrack[];

	console.log(
		`[subtitles] videoId=${options.youtubeVideoId}: found ${tracks.length} caption track(s): ` +
			`${tracks.map((t) => `${t.languageCode}(${t.kind ?? "manual"})`).join(", ") || "none"}`
	);

	const results: SubtitleResult[] = [];

	for (const lang of options.languages) {
		const manual = tracks.find(
			(t) => t.languageCode === lang && t.kind !== "asr"
		);
		const asr = tracks.find((t) => t.languageCode === lang && t.kind === "asr");
		const track = manual ?? (options.autoGenerated !== false ? asr : undefined);
		if (!track) {
			console.warn(
				`[subtitles] videoId=${options.youtubeVideoId}: no track found for lang=${lang} ` +
					`(autoGenerated=${options.autoGenerated})`
			);
			continue;
		}

		const source: SubtitleResult["source"] =
			track.kind === "asr" ? "auto_generated" : "youtube_captions";

		console.log(
			`[subtitles] videoId=${options.youtubeVideoId}: fetching ${source} track for lang=${lang}`
		);

		const captionRes = await fetch(track.baseUrl);
		if (!captionRes.ok) {
			console.error(
				`[subtitles] videoId=${options.youtubeVideoId}: caption URL fetch failed: ` +
					`${captionRes.status} ${captionRes.statusText} (lang=${lang}, source=${source})`
			);
			continue;
		}

		const rawData = await captionRes.text();
		console.log(
			`[subtitles] videoId=${options.youtubeVideoId}: fetched ${rawData.length} bytes for lang=${lang}`
		);
		results.push({
			language: lang,
			source,
			fullText: extractPlainText(rawData),
			rawData,
		});
	}

	return results;
}

// ─── Timed Segment Parsing ───────────────────────────────────────────────────

export interface TimedSegment {
	/** End time in seconds */
	end: number;
	/** Start time in seconds */
	start: number;
	/** Segment text content (HTML entities decoded, tags stripped) */
	text: string;
}

/**
 * Parse raw caption data into timed segments with start/end timestamps.
 *
 * Handles three formats:
 * 1. JSON3 (YouTube internal format with `events[].tStartMs/dDurationMs`)
 * 2. XML timedtext with `<text start="sec" dur="sec">` elements
 * 3. XML timedtext with `<p t="ms" d="ms">` elements
 */
export function parseTimedSegments(rawData: string): TimedSegment[] {
	// JSON3 format
	try {
		const parsed = JSON.parse(rawData) as {
			events?: {
				tStartMs?: number;
				dDurationMs?: number;
				segs?: { utf8?: string }[];
			}[];
		};
		if (parsed.events) {
			return parseJson3Events(parsed.events);
		}
	} catch {
		// Not JSON — try XML
	}

	// XML <text start="..." dur="..."> format (common from InnerTube)
	if (rawData.includes("<text")) {
		return parseXmlTextElements(rawData);
	}

	// XML <p t="..." d="..."> format (timedtext format=3)
	if (rawData.includes("<p ")) {
		return parseXmlPElements(rawData);
	}

	return [];
}

function parseJson3Events(
	events: {
		tStartMs?: number;
		dDurationMs?: number;
		segs?: { utf8?: string }[];
	}[]
): TimedSegment[] {
	const segments: TimedSegment[] = [];
	for (const event of events) {
		const text = (event.segs ?? [])
			.map((s) => s.utf8 ?? "")
			.join("")
			.trim();
		if (!text || event.tStartMs == null) {
			continue;
		}
		const startMs = event.tStartMs;
		const durMs = event.dDurationMs ?? 0;
		segments.push({
			start: startMs / 1000,
			end: (startMs + durMs) / 1000,
			text: decodeHtmlEntities(text),
		});
	}
	return segments;
}

const XML_TEXT_REGEX =
	/<text\s+start="([^"]+)"\s+dur="([^"]+)"[^>]*>([\s\S]*?)<\/text>/g;

function parseXmlTextElements(rawData: string): TimedSegment[] {
	const segments: TimedSegment[] = [];
	for (const match of rawData.matchAll(XML_TEXT_REGEX)) {
		const start = Number.parseFloat(match[1] ?? "");
		const dur = Number.parseFloat(match[2] ?? "");
		const text = stripTags(decodeHtmlEntities(match[3] ?? "")).trim();
		if (!(text && Number.isFinite(start) && Number.isFinite(dur))) {
			continue;
		}
		segments.push({ start, end: start + dur, text });
	}
	return segments;
}

const XML_P_REGEX = /<p\s+t="(\d+)"\s+d="(\d+)"[^>]*>([\s\S]*?)<\/p>/g;

function parseXmlPElements(rawData: string): TimedSegment[] {
	const segments: TimedSegment[] = [];
	for (const match of rawData.matchAll(XML_P_REGEX)) {
		const tMs = Number.parseInt(match[1] ?? "", 10);
		const dMs = Number.parseInt(match[2] ?? "", 10);
		const text = stripTags(decodeHtmlEntities(match[3] ?? "")).trim();
		if (!(text && Number.isFinite(tMs) && Number.isFinite(dMs))) {
			continue;
		}
		segments.push({ start: tMs / 1000, end: (tMs + dMs) / 1000, text });
	}
	return segments;
}

function stripTags(html: string): string {
	return html.replace(/<[^>]+>/g, "");
}

function decodeHtmlEntities(text: string): string {
	return text
		.replace(/&amp;/g, "&")
		.replace(/&lt;/g, "<")
		.replace(/&gt;/g, ">")
		.replace(/&quot;/g, '"')
		.replace(/&#39;/g, "'")
		.replace(/&nbsp;/g, " ");
}

/**
 * Extract plain text from caption data.
 *
 * Handles three formats in order:
 * 1. JSON3 (YouTube internal format with `events[].segs[].utf8`)
 * 2. XML timedtext (InnerTube API default — `<p t="..." d="...">text</p>`)
 * 3. WebVTT / SRT (fallback, strips timestamps and tags)
 */
function extractPlainText(rawData: string): string {
	// JSON3 (watch page or explicit &fmt=json3 request)
	try {
		const parsed = JSON.parse(rawData) as {
			events?: { segs?: { utf8?: string }[] }[];
		};
		if (parsed.events) {
			return parsed.events
				.flatMap((e) => e.segs?.map((s) => s.utf8) ?? [])
				.join("")
				.replace(/\n{3,}/g, "\n\n")
				.trim();
		}
	} catch {
		// Not JSON — continue
	}

	// XML timedtext (default from InnerTube API)
	if (
		rawData.trimStart().startsWith("<?xml") ||
		rawData.includes("<timedtext")
	) {
		return rawData
			.replace(/<[^>]+>/g, " ")
			.replace(/&amp;/g, "&")
			.replace(/&lt;/g, "<")
			.replace(/&gt;/g, ">")
			.replace(/&quot;/g, '"')
			.replace(/&#39;/g, "'")
			.replace(/\s+/g, " ")
			.trim();
	}

	// VTT / SRT fallback
	return rawData
		.replace(/<[^>]+>/g, "")
		.replace(/^\d+$/gm, "")
		.replace(
			/\d{2}:\d{2}:\d{2}[.,]\d{3}\s*-->\s*\d{2}:\d{2}:\d{2}[.,]\d{3}/g,
			""
		)
		.replace(/\n{3,}/g, "\n\n")
		.trim();
}
