import z from "zod";
import { fetchPlayerResponse } from "./page";

// ─── Schemas ─────────────────────────────────────────────────────────────────

export const subtitleOptionsSchema = z.object({
	youtubeVideoId: z.string().trim().min(1),
	languages: z.array(z.string()).default(["en"]),
	/** If true, try auto-generated captions when manual subs unavailable */
	autoGenerated: z.boolean().default(true),
});

export type SubtitleOptions = z.infer<typeof subtitleOptionsSchema>;

export interface SubtitleResult {
	/** Full text content of the subtitles */
	fullText: string;
	language: string;
	/** Raw subtitle data (JSON3 or VTT) */
	rawData: string;
	source: "youtube_captions" | "auto_generated";
}

// ─── Subtitles Implementation ────────────────────────────────────────────────

interface CaptionTrack {
	baseUrl: string;
	/** Present only on auto-generated tracks */
	kind?: string;
	languageCode: string;
}

/**
 * Download subtitles/captions for a YouTube video.
 *
 * Uses the InnerTube ANDROID client API which returns working caption
 * track URLs without session cookies, compatible with Cloudflare Workers.
 */
export async function getSubtitles(
	options: SubtitleOptions
): Promise<SubtitleResult[]> {
	const playerData = await fetchPlayerResponse(options.youtubeVideoId);

	const tracks = ((
		(playerData.captions as Record<string, unknown> | undefined)
			?.playerCaptionsTracklistRenderer as Record<string, unknown> | undefined
	)?.captionTracks ?? []) as CaptionTrack[];

	const results: SubtitleResult[] = [];

	for (const lang of options.languages) {
		const manual = tracks.find(
			(t) => t.languageCode === lang && t.kind !== "asr"
		);
		const asr = tracks.find((t) => t.languageCode === lang && t.kind === "asr");
		const track = manual ?? (options.autoGenerated !== false ? asr : undefined);
		if (!track) {
			continue;
		}

		const source: SubtitleResult["source"] =
			track.kind === "asr" ? "auto_generated" : "youtube_captions";

		const captionRes = await fetch(track.baseUrl);
		if (!captionRes.ok) {
			continue;
		}

		const rawData = await captionRes.text();
		results.push({
			language: lang,
			source,
			fullText: extractPlainText(rawData),
			rawData,
		});
	}

	return results;
}

/**
 * Extract plain text from caption data.
 *
 * Handles three formats in order:
 * 1. JSON3 (YouTube internal format with `events[].segs[].utf8`)
 * 2. XML timedtext (InnerTube API default — `<p t="..." d="...">text</p>`)
 * 3. WebVTT / SRT (fallback, strips timestamps and tags)
 */
function extractPlainText(rawData: string): string {
	// JSON3 (watch page or explicit &fmt=json3 request)
	try {
		const parsed = JSON.parse(rawData) as {
			events?: { segs?: { utf8?: string }[] }[];
		};
		if (parsed.events) {
			return parsed.events
				.flatMap((e) => e.segs?.map((s) => s.utf8) ?? [])
				.join("")
				.replace(/\n{3,}/g, "\n\n")
				.trim();
		}
	} catch {
		// Not JSON — continue
	}

	// XML timedtext (default from InnerTube API)
	if (
		rawData.trimStart().startsWith("<?xml") ||
		rawData.includes("<timedtext")
	) {
		return rawData
			.replace(/<[^>]+>/g, " ")
			.replace(/&amp;/g, "&")
			.replace(/&lt;/g, "<")
			.replace(/&gt;/g, ">")
			.replace(/&quot;/g, '"')
			.replace(/&#39;/g, "'")
			.replace(/\s+/g, " ")
			.trim();
	}

	// VTT / SRT fallback
	return rawData
		.replace(/<[^>]+>/g, "")
		.replace(/^\d+$/gm, "")
		.replace(
			/\d{2}:\d{2}:\d{2}[.,]\d{3}\s*-->\s*\d{2}:\d{2}:\d{2}[.,]\d{3}/g,
			""
		)
		.replace(/\n{3,}/g, "\n\n")
		.trim();
}
